version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: '20:00'
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: jasmine
    versions:
    - ">= 3.0.a, < 4"
