services: memcache

bundler_args: --without development

rvm:
  - 1.9.3
  - 2.0.0

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - DAEMON=1 bundle exec rake server

script: COVERAGE=simplecov bundle exec rake spec test

env:
  - TEST_MODE=rack
  - TEST_MODE=rdb
  - TEST_MODE=webrick
  - TEST_MODE=secure

notifications:
  irc: "irc.freenode.org#tdiary"

matrix:
  allow_failures:
    # webrick mode is unstable results...
    - env: TEST_MODE=webrick
