language: ruby

services: memcache

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head

cache: bundler

# ignored --deployment option
bundler_args: "--without server"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "echo 'gemspec' > Gemfile.local"

before_script:
  - DAEMON=1 bundle exec rake server
  - npm install
  - grunt

script: if [ $TEST_MODE = "gem" ] ; then bundle exec tdiary test ; else bundle exec rake spec jasmine:ci test ; fi

env:
  - TEST_MODE=rack
  - TEST_MODE=webrick
  - TEST_MODE=secure
  - TEST_MODE=gem

notifications:
  irc: "irc.freenode.org#tdiary"

matrix:
  allow_failures:
    # webrick mode is unstable results...
    - env: TEST_MODE=webrick
